# fly.toml app configuration file generated for part3-front-end on 2024-03-25T19:20:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part3-front-end'
primary_region = 'arn'

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
